# .github/workflows/main.yml
name: Trigger docker-compose

on:
  pull_request:
    types:
      - opened
    branches:
      - main

env:
  MANIFEST: .github/manifest.json

jobs:
  prepare-matrix:
    if: startsWith(github.actor, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch info
        id: info
        run: |
          IMAGE_NAME=$(echo "${{ github.event.pull_request.title }}" | grep -oP '\[\K[^\]]*')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Set dynamic key name
        id: set-key
        run: |
          echo "key_name=${{ steps.info.outputs.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Read manifest.json and extract matrix
        id: set-matrix
        run: |
          import json
          import os

          key_name = os.getenv("key_name")
          manifest_path = os.getenv("MANIFEST")
          with open(manifest_path) as f:
              data = json.load(f)

          matrix = {"key": data[key_name]}
          with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
              print(f"matrix={json.dumps(matrix)}", file=output)
        shell: python

  run-action:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom action
        uses: ./.github/actions
        with:
          branch: ${{ matrix.key.branch }}
          workflow_id: ${{ matrix.key.workflow_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  finalize:
    needs: run-action
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Final summary step
        run: echo "All matrix jobs completed successfully. Finalizing workflow."
