name: Dev Branch Workflow
on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  dev-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4

      - name: Pass
        run: |
          echo 1
