name: Docker-compose (Sonarr)

on:
  push:
    branches: [sonarr]
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'What triggered this workflow'
        required: false
        default: 'manual'
      run_id:
        description: 'Main workflow run ID'
        required: false

env:
  MANIFEST: .github/manifest.json
  
jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jinja-cli
        run: |
          pip3 install jinja-cli

      - name: Create .env
        run: |
          jinja env.j2 --data ${{ env.MANIFEST }} > .env

      - name: Docker Compose up
        run: |
          docker compose up -d
          
      - name: Test Sonarr HTTP response
        run: |
          EXTERNAL_SONARR_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.sonarr_port')
          SONARR_URL=http://localhost:$EXTERNAL_SONARR_PORT
          for i in {1..30}; do
            if curl --silent --fail $SONARR_URL > /dev/null; then
              echo "Sonarr is up!"
              break
            fi
            echo "Waiting for Sonarr... ($i)"
            sleep 1
          done
          curl --fail $SONARR_URL || (echo "Sonarr did not respond" && exit 1)

      - name: Test qBittorrent HTTP response
        run: |
          EXTERNAL_QBITTORRENT_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.sonarr_qbittorent_port')
          QBITTORRENT_URL=http://localhost:$EXTERNAL_QBITTORRENT_PORT
          for i in {1..30}; do
            if curl --silent --fail $QBITTORRENT_URL > /dev/null; then
              echo "qBittorrent is up!"
              break
            fi
            echo "Waiting for qBittorrent... ($i)"
            sleep 1
          done
          curl --fail $QBITTORRENT_URL || (echo "qBittorrent did not respond" && exit 1)

      - name: Tear down Docker Compose
        run: docker compose down --volumes
