name: Renovate Package Update Trigger

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  detect-renovate-update:
    if: startsWith(github.actor, 'renovate')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Extract package name from PR title
        id: extract
        run: |
          echo "${{ github.event.pull_request.title }}"
          IMAGE_NAME=$(echo "${{ github.event.pull_request.title }}" | grep -oP '\[\K[^\]]*')
          echo $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Use output
        run: |
          echo "${{ steps.extract.outputs.IMAGE_NAME }}"