name: Docker-compose (Node-Exporter-Alpine)

on:
  push:
    branches: 
      - node-exporter-alpine
      - node-exporter-alpine-dev
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'What triggered this workflow'
        required: false
        default: 'manual'
      run_id:
        description: 'Main workflow run ID'
        required: false

env:
  MANIFEST: .github/manifest.json
  
jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jinja-cli
        run: |
          pip3 install jinja-cli

      - name: Create .env
        run: |
          jinja env.j2 --data ${{ env.MANIFEST }} > .env
      
      - name: Run dind
        run: |
          docker run -d --privileged --name dind-compose \
            -v $(pwd):/workspace \
            -p 9100:9100 \
            docker:dind
          
          sleep 5
          docker exec dind-compose sh -c "apk add --no-cache docker-compose"
          
          docker exec -w /workspace dind-compose docker-compose up -d
      
      - name: test
        run: |
          curl http://localhost:9100

