name: Docker-compose (Prometheus)

on:
  push:
    branches: [prometheus]
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'What triggered this workflow'
        required: false
        default: 'manual'
      run_id:
        description: 'Main workflow run ID'
        required: false

env:
  MANIFEST: .github/manifest.json

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jinja-cli
        run: |
          pip3 install jinja-cli

      - name: Create .env
        run: |
          jinja env.j2 --data ${{ env.MANIFEST }} > .env
          
      - name: Create dirs and config
        run: |
          PROMETHEUS_CONFIG=$(cat ${{ env.MANIFEST }} | jq -r '.PROMETHEUS_CONFIG')
          PROMETHEUS_DATA=$(cat ${{ env.MANIFEST }} | jq -r '.PROMETHEUS_DATA')
          mkdir -p $PROMETHEUS_CONFIG
          mkdir -p $PROMETHEUS_DATA
          chmod 755 $PROMETHEUS_CONFIG
          chmod 777 $PROMETHEUS_DATA
          jinja prometheus.j2 --data ${{ env.MANIFEST }} > $PROMETHEUS_CONFIG/prometheus.yml

      - name: Docker Compose up
        run: |
          docker compose up -d
          
      - name: Test HTTP response
        run: |
          PROMETHEUS_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.PROMETHEUS_PORT')
          URL=http://localhost:$PROMETHEUS_PORT
          for i in {1..30}; do
            if curl --silent --fail $URL > /dev/null; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for Service... ($i)"
            sleep 1
          done
          curl --fail $URL || (echo "Service did not respond" && exit 1)

      - name: Tear down Docker Compose
        run: docker compose down --volumes
