name: Docker-compose (Jellyfin)

on:
  push:
    branches: [jellyfin]
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'What triggered this workflow'
        required: false
        default: 'manual'
      run_id:
        description: 'Main workflow run ID'
        required: false
  
env:
  MANIFEST: .github/manifest.json

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jinja-cli
        run: |
          pip3 install jinja-cli

      - name: Create .env
        run: |
          jinja env.j2 --data ${{ env.MANIFEST }} > .env

      - name: Docker Compose up
        run: |
          docker compose up -d
          
      - name: Test HTTP response
        run: |
          JELLYFIN_WEB_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.JELLYFIN_WEB_PORT')
          URL=http://localhost:$JELLYFIN_WEB_PORT
          for i in {1..30}; do
            if curl --silent --fail $URL > /dev/null; then
              echo "Service is up!"
              break
            fi
            echo "Waiting for Service... ($i)"
            sleep 1
          done
          curl --fail $URL || (echo "Service did not respond" && exit 1)

      - name: Tear down Docker Compose
        run: docker compose down --volumes
