name: Merge Action (main)

on:
  pull_request:
    types:
      - closed

jobs:
  main-merged-action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo The PR was merged

      - name: show actor
        run: |
          echo "${{ github.actor }}"