name: Docker-compose (Node-Exporter-Alpine)

on:
  push:
    branches: 
      - node-exporter-alpine
      - node-exporter-alpine-dev
    paths-ignore:
      - README.md
      - .gitignore
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'What triggered this workflow'
        required: false
        default: 'manual'
      run_id:
        description: 'Main workflow run ID'
        required: false

env:
  MANIFEST: .github/manifest.json
  DIND_CONTAINER_NAME: dind-compose
  
jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jinja-cli
        run: |
          pip3 install jinja-cli

      - name: Create .env
        run: |
          jinja env.j2 --data ${{ env.MANIFEST }} > .env
      
      - name: Run dind
        id: setup-dind
        run: |
          NODE_EXPORTER_PORT=$(cat ${{ env.MANIFEST }} | jq -r '.NODE_EXPORTER_PORT')
          docker run -d --privileged --name ${{ env.DIND_CONTAINER_NAME }} \
            -v $(pwd):/workspace \
            -p $NODE_EXPORTER_PORT:$NODE_EXPORTER_PORT \
            docker:dind
          
          sleep 5
          docker exec ${{ env.DIND_CONTAINER_NAME }} sh -c "apk add --no-cache docker-compose"
          
          docker exec -w /workspace ${{ env.DIND_CONTAINER_NAME }} docker-compose up -d

          echo "NODE_EXPORTER_PORT=$NODE_EXPORTER_PORT" >> $GITHUB_OUTPUT
          
      
      - name: test
        run: |
          curl http://localhost:9100
          echo ${{ steps.setup-dind.outputs.NODE_EXPORTER_PORT }}"
